---
_merge:
  - version
  - dependencies
  - devDependencies

name: aotds-docks
description: Full Thrust ship builder

author: 'Yanick Champoux <yanick@babyl.ca>'

scripts:
  build: NODE_ENV=production webpack
  start: webpack-dev-server --open --content-base public

  package: ./scripts/merge_package.pl

  test: tap 'src/**test.js' --no-coverage

  "lint:prettier": ./scripts/prettier
  "lint:eslint": ./scripts/eslint
  lint: npm-run-all --parallel "lint:prettier -- {@}" "lint:eslint -- {@}" --

  "lint:prettier:fix": npm run lint:prettier -- --fix
  "lint:eslint:fix": npm run lint:eslint -- --fix
  "lint:fix": npm-run-all "lint:eslint:fix -- {@}" "lint:prettier:fix -- {@}" --

eslintConfig:
  env:
    amd: true
    browser: true
    es6: true
    node: true
  extends:
  - prettier
  - eslint:recommended
  - plugin:you-dont-need-lodash-underscore/compatible
  - plugin:lodash/recommended
  ignorePatterns:
  - src/node_modules
  overrides:
  - files:
    - '*.svelte'
    processor: svelte3/svelte3
  parserOptions:
    ecmaFeatures:
      modules: true
    ecmaVersion: '2020'
    sourceType: module
  plugins:
  - svelte3
  rules:
    lodash/prefer-lodash-method: off
keywords: [ game ]
license: ISC
main: index.js

prettier:
  svelteSortOrder: markup-scripts-styles
  svelteStrictMode: false

tap:
    coverage: false
